[build-system]
requires = [
	"flit_core >=3.2,<4",
	]
build-backend = "flit_core.buildapi"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[project]
name = "HMM"
authors = [{name = "Justin Sim", email = "justin.sim@ucsf.edu"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "pytest" , "numpy"
]
requires-python=">3.7"


[project.urls]
Home = "https://github.com/justinsim12/HW6-HMM"